language: perl

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov Dist::Zilla::App::Command::cover

script:
  - dzil cover

after_success:
  - test $TRAVIS_PERL_VERSION = '5.20' && cd .build/*/ && cover -report codecov
