---
abstract: 'AVM Fritz!Box interaction via TR-064'
author:
  - 'Christian Garbs <mitch@cgarbs.de>'
build_requires:
  Test::Exception: '0'
  Test::Mock::LWP::Dispatch: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4218, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Fritz
provides:
  Net::Fritz:
    file: lib/Net/Fritz.pm
    version: v0.0.1
  Net::Fritz::Action:
    file: lib/Net/Fritz/Action.pm
  Net::Fritz::Box:
    file: lib/Net/Fritz/Box.pm
  Net::Fritz::Data:
    file: lib/Net/Fritz/Data.pm
  Net::Fritz::Device:
    file: lib/Net/Fritz/Device.pm
  Net::Fritz::Error:
    file: lib/Net/Fritz/Error.pm
  Net::Fritz::IsNoError:
    file: lib/Net/Fritz/IsNoError.pm
  Net::Fritz::Service:
    file: lib/Net/Fritz/Service.pm
requires:
  Digest::MD5: '0'
  LWP::UserAgent: '0'
  Moo: '0'
  SOAP::Lite: '0'
  XML::Simple: '0'
version: v0.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
